version: '3'

services:
  orders-db:
    container_name: orders_database
    image: mysql:8
    restart: always
    volumes:
      - ./Persistencia:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: DB_Orders
